//! `SURYA_*` with a one-release `ZERON_*` fallback.
//!
//! Generated by `scripts/rename-apply.sh`. A user's shell profile, systemd
//! `EnvironmentFile` or CI secret still says `ZERON_*`; reading it keeps them
//! working for one release, and the warning tells them what to change. Drop
//! this module and its call sites the release after.
//!
//! It lives in proto because that is the crate everything else already
//! depends on, and the signatures mirror `std::env` exactly - `var` returns
//! the same `Result`, `var_os` the same `Option` - so a call site keeps its
//! `.ok()`, `.is_err()` or `.unwrap_or_else(|_| …)` unchanged.

use std::env::VarError;
use std::ffi::OsString;
use std::sync::OnceLock;

/// The variables a USER sets by hand, from `daemon.rs CAPTURED_ENV` and
/// `main.rs`. Dev and test knobs (`SURYA_MOCK_*`, `SURYA_DEMO_*`,
/// `SURYA_ACP_*`, and the rest) are deliberately absent: nothing outside this
/// repo sets them, so they rename without an alias.
pub const ALIASED: &[&str] = &[
    "DATA_DIR",
    "EDGE_URL",
    "EDGE_TOKEN",
    "ORG_ID",
    "WORKOS_CLIENT_ID",
    "WORKOS_API_BASE",
    "IPC_PORT",
    "BIND",
    "IPC_TOKEN",
    "CALLBACK_PORT",
    "HARNESS",
    "DEVICE_NAME",
    "ENGINE",
    "ENGINE_TOKEN",
    "USER_ID",
    "WORKTREES_DIR",
];

fn warned() -> &'static std::sync::Mutex<std::collections::HashSet<String>> {
    static WARNED: OnceLock<std::sync::Mutex<std::collections::HashSet<String>>> = OnceLock::new();
    WARNED.get_or_init(Default::default)
}

fn warn_once(name: &str) {
    if let Ok(mut seen) = warned().lock()
        && seen.insert(name.to_owned())
    {
        tracing::warn!("renamed env var ZERON_{name}, use SURYA_{name}");
    }
}

/// `SURYA_<name>`, else `ZERON_<name>` with a warning logged once per name.
/// Same `Option` as [`std::env::var_os`].
pub fn var_os(name: &str) -> Option<OsString> {
    if let Some(value) = std::env::var_os(format!("SURYA_{name}")) {
        return Some(value);
    }
    let old = std::env::var_os(format!("ZERON_{name}"))?;
    warn_once(name);
    Some(old)
}

/// `SURYA_<name>`, else `ZERON_<name>` with a warning logged once per name.
/// Same `Result` as [`std::env::var`], so `.ok()` and `.is_err()` still work.
pub fn var(name: &str) -> Result<String, VarError> {
    match std::env::var(format!("SURYA_{name}")) {
        Ok(value) => Ok(value),
        Err(VarError::NotPresent) => {
            let old = std::env::var(format!("ZERON_{name}"));
            if old.is_ok() {
                warn_once(name);
            }
            old
        }
        // A SURYA_* that is set but not UTF-8 is the user's own mistake and is
        // reported as such, not silently replaced by the old name.
        Err(other) => Err(other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The helper adds the prefix, so a `SURYA_` left in this list would read
    /// `SURYA_SURYA_…`.
    #[test]
    fn the_aliased_names_carry_no_prefix() {
        for name in ALIASED {
            assert!(!name.starts_with("SURYA_"), "{name}");
            assert!(!name.starts_with("ZERON_"), "{name}");
        }
        assert_eq!(ALIASED.len(), 16, "the user-set set from the rename plan");
    }

    /// New name wins, old name still works, neither set reads as unset.
    /// One process, one variable, so the warning set is not a shared fixture.
    #[test]
    fn the_new_name_wins_and_the_old_one_still_works() {
        let name = "RENAME_PROBE";
        // SAFETY: single-threaded test, and this variable is used nowhere else.
        unsafe {
            std::env::remove_var("SURYA_RENAME_PROBE");
            std::env::remove_var("ZERON_RENAME_PROBE");
        }
        assert!(var(name).is_err(), "unset");
        assert_eq!(var_os(name), None);

        unsafe { std::env::set_var("ZERON_RENAME_PROBE", "old") };
        assert_eq!(var(name).as_deref(), Ok("old"), "the old name is honoured");

        unsafe { std::env::set_var("SURYA_RENAME_PROBE", "new") };
        assert_eq!(var(name).as_deref(), Ok("new"), "the new name wins");

        unsafe {
            std::env::remove_var("SURYA_RENAME_PROBE");
            std::env::remove_var("ZERON_RENAME_PROBE");
        }
    }
}
